config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: %i(passwords registrations)
  root 'welcome#index'
  resources :likes , only: %i(update)

  namespace :dashboard do
    root 'base#index'
    resources :domains
    resources :offers
    resources :categories
  end

  resources :domains do
    resources :offers, only: %i(new create)
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :domains
  validates :name, presence: true
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  include Filterable
  extend FriendlyId

  friendly_id :name, use: [:slugged, :finders]

  has_many :offers
  has_and_belongs_to_many :categories
  accepts_nested_attributes_for :categories

  enum status: %w(active inactive pending sold)

  default_scope { order('created_at ASC') }
  scope :starts_with, -> (alphabet) { where("name like ?", "#{ alphabet }%")}

  has_attached_file :logo, styles: { medium: "400x230>", thumb: "300x150>" }, default_url: "http://placehold.it/400x230"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/

  validates :name, :logo, :status, presence: true

  before_save :normalize!

  def self.category(name)
    Category.find_by(name: name).domains
  end

  def normalize!
    self.name = self.name.downcase
  end
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :domain, counter_cache: true
  enum status: %w(contact_buyer pending_transaction accepted)
  default_scope { order('created_at ASC') }

  validates :name, :email, :amount, :message , presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  before_action :authenticate_user!

  def index
    @domains = Domain.all
  end
end

app/controllers/dashboard/categories_controller.rb
class Dashboard::CategoriesController <  Dashboard::BaseController
  before_action :get_category, only: %i(edit update delete)
  before_action :category, only: %i(new create)

  def index
    @categories = Category.all
  end

  def create
    @category.assign_attributes(category_params)

    if @category.save
      flash.now[:success] = 'Successfylly created a category.'
      redirect_to dashboard_categories_path
    else
      render :new
    end
  end

  def update
    @category.assign_attributes(category_params)

    if @category.save
      flash.now[:success] = 'Successfylly created a category.'
      redirect_to dashboard_categories_path
    else
      render :edit
    end
  end

  private

  def category
    @category = Category.new
  end

  def get_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :featured)
  end
end

app/controllers/dashboard/domains_controller.rb
class Dashboard::DomainsController <  Dashboard::BaseController
  before_action :get_domain, only: %i(edit update delete)
  before_action :domain, only: %i(new create)

  def create
    @domain.assign_attributes(domain_params)

    if @domain.save
      flash.now[:success] = 'Successfylly created a domain.'
      redirect_to dashboard_domains_path
    else
      render :new
    end
  end

  def update
    @domain.assign_attributes(domain_params)

    if @domain.save
      flash.now[:success] = 'Successfylly updated a domain.'
      redirect_to dashboard_domains_path
    else
      render :edit
    end
  end

  private

  def domain
    @domain = Domain.new
  end

  def get_domain
    @domain = Domain.find(params[:id])
  end

  def domain_params
    params.require(:domain).permit(:name, :status, :logo, category_ids: [])
  end
end

app/controllers/dashboard/offers_controller.rb
class Dashboard::OffersController < Dashboard::BaseController
  before_action :get_offer, only: %i(update show)

  def index
    @offers = Offer.all
  end

  def create
  end

  def update
    @offer.assign_attributes(offer_params)

    if @offer.save
      flash.now[:success] = 'Successfylly updated an offer.'
      redirect_to dashboard_offers_path
    else
      render :show
    end
  end

  private

  def offer_params
    params.require(:offer).permit(:status)
  end

  def get_offer
    @offer = Offer.find(params[:id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def update
    @domain = Domain.find(params[:id])
    @domain.increment(:likes, by = 1)

    if @domain.save
      redirect_to :back, flash: { notice: "Thanks, how about an offer as well" }
    else
      redirect_to :back, flash: { alert: 'Something went wrong, lets try again' }
    end
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :get_domain

  def create
    @offer.assign_attributes(offer_params)

    if @offer.save
      redirect_to :root, flash: { notice: 'Thanks, we have received your offer, we will get back to you as soon as possible.' }
    else
      render :new
    end
  end

  private

  def get_domain
    @domain = Domain.find(params[:domain_id])
    @offer = @domain.offers.new
  end

  def offer_params
    params.require(:offer).permit(:name, :email, :company, :amount, :message)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @categories = Category.all
    @domains = Domain.where(status: 'active')
                     .filter(params.slice(:starts_with, :category))
                     .page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/base/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-sm-6">
      <h3>Your Domains</h3>
      <br />
    </div>

    <div class="col-md-6 col-sm-6">
      <%= link_to 'Add Domain', new_dashboard_domain_path, class: 'btn btn-md btn-primary pull-right' %>
    </div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>Domain Name</th>
        <th>Status</th>
        <th>Offers</th>
        <th>Categories</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @domains.each do |domain| %>
        <tr>
          <td><%= domain.name %></td>
          <td><%= domain.status %></td>
          <td><%= domain.offers.count %></td>
          <td>
            <% domain.categories.each do |category | %>
              <span class="label label-default"><%= category.name %></span>
            <% end %>
          </td>
          <td><%= link_to '<span class="ion-edit"></span>'.html_safe, edit_dashboard_domain_path(domain) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

 <%#<a id="demo" href="#animatedModal">DEMO</a>%>
 <%#<div id="animatedModal">%>
   <%#<center>%>
     <%#<a href="" class="close-animatedModal ion-ios-close-outline icon-close"> </a>%>
   <%#</center>%>

  <%#<div class="container">%>
    <%#Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.%>
  <%#</div>%>

<%#<script>%>
  <%#$("#demo").animatedModal();%>
<%#</script>%>

app/views/dashboard/categories/_form.html.erb
<div class="col-sm-12 col-md-6 col-md-offset-3">
  <%= simple_form_for @category, url: path do |f| %>
    <%= f.input :name %>
    <%= f.input :featured %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/dashboard/categories/edit.html.erb
<div class="container">
  <legend>Edit Category</legend>

  <br>
  <%= render 'form', path: dashboard_category_path(@category) %>
</div>

app/views/dashboard/categories/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-sm-6">
      <h3>List of Categories</h3>
      <br />
    </div>

    <div class="col-md-6 col-sm-6">
      <%= link_to 'Add New Category', new_dashboard_category_path, class: 'btn btn-md btn-primary pull-right' %>
    </div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Featured</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td><%= category.featured %></td>
          <td><%= link_to '<span class="ion-edit"></span>'.html_safe, edit_dashboard_category_path(category) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dashboard/categories/new.html.erb
<div class="container">
  <legend>Create New Category</legend>

  <br>
  <%= render 'form', path: dashboard_categories_path %>
</div>

app/views/dashboard/domains/_form.html.erb
<div class="col-sm-12 col-md-8 col-md-offset-2">
  <%= simple_form_for @domain, url: path do |f| %>
    <div class="row">
      <div class="col-md-6">
        <%= f.input :logo, type: :file, label: false %>
      </div>

      <div class="col-md-6">
        <%= f.input :name %>
        <%= f.input :status, as: :select, collection: Domain.statuses.keys %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <%= f.input :starting_offers %>
      </div>

      <div class="col-md-6">
        <%= f.input :likes, label: 'Starting Likes' %>
      </div>
    </div>

    <%= f.association :categories %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/dashboard/domains/edit.html.erb
<div class="container">
  <legend>Update Domain</legend>

  <br>
  <%= render 'form', path: dashboard_domain_path(@domain) %>
</div>

app/views/dashboard/domains/new.html.erb
<div class="container">
  <legend>Add a new Domain</legend>

  <br>
  <%= render 'form', path: dashboard_domains_path %>
</div>

app/views/dashboard/offers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-sm-6">
      <h3>Your Domains</h3>
      <br />
    </div>

    <div class="col-md-6 col-sm-6">
      <%= link_to 'Add Domain', new_dashboard_domain_path, class: 'btn btn-md btn-primary pull-right' %>
    </div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>Domain</th>
        <th>Name</th>
        <th>Status</th>
        <th>Company</th>
        <th>Amount</th>
        <th>Date</th>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @offers.each do |offer| %>
        <tr>
          <td><%= offer.domain.name %></td>
          <td><%= offer.name %></td>
          <td><%= offer.email %></td>
          <td><%= offer.company %></td>
          <td><%= number_to_currency(offer.amount) %></td>
          <td><%= offer.created_at.stamp('Jan 05, 2015') %></td>
          <td><%= offer.status.try(:humanize) %></td>
          <td><%= link_to '<span class="ion-edit"></span>'.html_safe, dashboard_offer_path(offer) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dashboard/offers/show.html.erb
<div class="container">
  <legend>Offer</legend>

  <br>

  <div class="col-sm-12">
    <div class="col-md-12">
      <p><strong>Domain: </strong> <%= @offer.domain.name %></p>
      <p><strong>Name: </strong> <%= @offer.name %></p>
      <p><strong>Email: </strong> <%= @offer.email %></p>
      <p><strong>Amount: </strong> <%= number_to_currency(@offer.amount) %></p>
      <p><strong>Message: </strong> <%= @offer.message %></p>
    </div>

    <%= simple_form_for @offer, url: dashboard_offer_path do |f| %>
      <div class="col-md-4">
        <%= f.input :status, as: :select, collection: Offer.statuses.keys %>
        <%= f.button :submit %>
      </div>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Domazone : Start your dream business with these amazing domains</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <link rel="stylesheet" href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.2.0/animate.min.css">
</head>
<body>
  <%= render 'shared/flash' %>
  <%= render 'shared/nav' %>
  <%= yield %>
</body>
</html>

app/views/offers/new.html.erb
<div class="container">
  <h3> Make an offer <small>Some offers are just too hard to deny, lets make one of those.</small></h3>
  <hr>
  <br>
  <br>
  <br>
  <div class="col-md-4">
    <div class="thumbnail" style="border: 3px solid #FAFAF6;">
      <%= link_to "<i class='ion-ios-heart text-primary' data-toggle='tooltip' data-placement='top' title='#{@domain.likes} Likes'></i>".html_safe, like_path(@domain), class: 'icon-right', method: :put %>
      <i class="ion-cash text-green icon-left help" data-toggle="tooltip" data-placement="top" title="<%= @domain.offers_count.to_i + @domain.starting_offers.to_i %> offers"></i>
      <%= image_tag(@domain.logo.url(:medium), class: 'img-responsive') %>
      <div class="caption">
        <h4 class="" style="color: #696975;"><%= @domain.name %></h4>
      </div>
    </div>
  </div>

  <div class="col-md-6 col-md-offset-1">
    <%= simple_form_for @offer, url: domain_offers_path(@domain) do |f| %>
      <div class="row">
        <div class="col-md-6"><%= f.input :name %></div>
        <div class="col-md-6"><%= f.input :email %></div>
      </div>

      <div class="row">
        <div class="col-md-6"><%= f.input :company %></div>
        <div class="col-md-6"><%= f.input :amount %></div>
      </div>
      <%= f.input :message, input_html: { rows: 4 } %>
      <%= f.submit 'Submit Offer', class: 'btn btn-primary pull-right' %>
    <% end %>
  </div>
</div>

app/views/shared/_flash.html.erb
<% if alert %>
  <div class="alert alert-dismissible alert-danger">
    <div class="container">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong>Oh Snap! </strong><%= alert %>.
    </div>
  </div>
<% elsif notice %>
  <div class="alert alert-dismissible alert-success">
    <div class="container">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong>Awesome! </strong><%= notice %>.
    </div>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= image_tag('logo.png') %></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Domains', dashboard_root_path %></li>
          <li><%= link_to 'Offers', dashboard_offers_path %></li>
          <li><%= link_to 'Categories', dashboard_categories_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link'  %></li>
        <% else %>
          <!--
          <li><a href="#">Premium Domains</a></li>
          <li><a href="#">3 Letter Domains</a></li>
          <li><a href="#">Dictionary Domains</a></li>
          -->
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/welcome/index.html.erb
<div class="jumbotron" style="margin-top: -25px !important; padding: 50px;">
  <div class="container">
    <h1>Premium Domains</h1>
    <p>Start your dream business with these amazing domains.</p>
    <p><a class="btn btn-primary btn-lg">Check'em Out</a></p>
  </div>
</div>

<div class="container">
  <div class="dropdown col-md-2">
    <button class="btn btn-sm btn-default dropdown-toggle btn-block" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      Filter By
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
      <% @categories.each do |category| %>
        <li><%= link_to category.name, root_path(category: category.name) %></li>
      <% end %>
    </ul>
  </div>

  <div class="col-md-10 col-sm-12">
    <% ('A'..'Z').to_a.each do |alphabet| %>
      <%= link_to alphabet, root_path(starts_with: alphabet.downcase), class: 'alphabet' %>
    <% end %>
  </div>

  <br>
  <br>
  <hr>

  <% @domains.each do |domain| %>
    <div class="col-md-3">
      <div class="thumbnail" style="border: 3px solid #FAFAF6;">
        <%= link_to "<i class='ion-ios-heart text-primary' data-toggle='tooltip' data-placement='top' title='#{domain.likes} Likes'></i>".html_safe, like_path(domain), class: 'icon-right', method: :put %>
        <i class="ion-cash text-green icon-left help" data-toggle="tooltip" data-placement="top" title="<%= domain.offers_count.to_i + domain.starting_offers.to_i %> offers"></i>
        <%= image_tag(domain.logo.url(:thumb), class: 'home-logo-image') %>
        <div class="caption">
          <h4 class="" style="color: #696975;"><%= domain.name %></h4>
          <%= link_to 'MAKE AN OFFER', new_domain_offer_path(domain) %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="col-md-12">
    <%= paginate @domains, theme: 'twitter-bootstrap-3', pagination_class: "pagination-small pull-right" %>
  </div>
</div>